Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = false
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.provision "file", source: "./ansible.repo", destination: "/tmp/ansible.repo"
  config.vm.provision "shell", path: "./install_ansible.sh"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.install = "false"
  end
  config.vm.define "cluster1" do |cluster1|
    cluster1.vm.box = "centos/7"
    cluster1.vm.network "private_network", ip: "192.168.50.4"
    cluster1.vm.hostname = "centosbox01.local.lab"
    cluster1.vm.provider "virtualbox" do |vb|
     unless File.exist?('./cluster1.vdi')
      vb.customize ['createmedium', '--filename', './cluster1.vdi', '--variant', 'Standard', '--size', '50']
     end
     vb.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', './cluster1.vdi']
    end
  end
  config.vm.define "cluster2" do |cluster2|
    cluster2.vm.box = "centos/7"
    cluster2.vm.network "private_network", ip: "192.168.50.5"
    cluster2.vm.hostname = "centosbox02.local.lab"
    cluster2.vm.provider "virtualbox" do |vb|
     unless File.exist?('./cluster2.vdi')
      vb.customize ['createmedium', '--filename', './cluster2.vdi', '--variant', 'Standard', '--size', '50']
     end
     vb.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', './cluster2.vdi']
    end
  end
end
