Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: "*.img"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.cputopology :sockets => '1', :cores => '2', :threads => '1'
    libvirt.nested = true
    libvirt.memory=2048
    libvirt.driver = 'kvm'
    libvirt.storage :file, :size => '4G'
    libvirt.cpu_mode = 'custom'
    libvirt.cpu_model = 'SandyBridge'
    libvirt.cpu_fallback = 'forbid'
    libvirt.machine_type = 'q35'
    libvirt.nic_model_type = 'e1000'
    libvirt.machine_arch = 'x86_64'
    libvirt.disk_bus = 'sata'
    libvirt.qemuargs :value => "-device"
    libvirt.qemuargs :value => "intel-iommu,intremap=off,caching-mode=off"
  end

  config.vm.define "xenserver" do |xenserver|
    xenserver.vm.network :private_network,
            :ip => "192.168.50.2",
            :libvirt__network_name => "xen_net",
            :libvirt__dhcp_enabled => false,
            :libvirt__host_ip => "192.168.50.1",
            :libvirt__netmask => "255.255.255.0",
            :libvirt__network_address => "192.168.50.0",
            :libvirt__domain_name => "local.lab"
    xenserver.vm.box = "debian/jessie64"
    xenserver.vm.hostname = "xenserver.local.lab"
    xenserver.vm.provision "file", source: "./config/interfaces", destination: "/tmp/interfaces"
    xenserver.vm.provision "file", source: "./config/sources.list", destination: "/tmp/sources.list"
    xenserver.vm.provision "shell", path: "./scripts/config-net-vagrant.sh"
    xenserver.vm.provision "shell", path: "./scripts/install-xen.sh"
  end
end
